exclude: '^$|venv'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        args: ['--line-length=79']
        language_version: python3.13
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML, types-Flask, types-Werkzeug, types-Markdown]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      -   id: pyupgrade
          args: [--py38-plus]
