name: Publish

on: [push]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install xelatex
        run: sudo apt-get install -y texlive-xetex texlive-fonts-extra fonts-ebgaramond
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download fonts
        run: npm install
      - name: Build Pages Only
        run: PYTHONPATH=. invoke build && tree && test -f content/extra/cv.pdf
      - name: Build Pages and Publish
        if: github.ref == 'refs/heads/master'
        run: PYTHONPATH=. invoke publish && tree dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
